import React from 'react';

export const FrameworkBadge = ({ tag }) => <span className='badge framework'>{tag}</span>;
export const RiskHeatBadge = ({ risk }) => <span className={`badge risk ${risk.toLowerCase()}`}>{risk}</span>;
export const CIAImpactChips = ({ value }) => <div className='chips'>{String(value).split(',').map((v) => <span key={v} className='chip'>{v.trim()}</span>)}</div>;
const STEPS = ['Mission Brief', 'Evidence Request', 'Evidence Evaluation', 'Client Response', 'Follow-Up Challenge', 'Consultant Debrief', 'Fundamentals', 'Framework Relevance'];
export function ProgressStepper({ currentStep }) { return <div className='stepper'>{STEPS.map((s, i) => <div key={s} className={`step ${i === currentStep ? 'active' : i < currentStep ? 'done' : ''}`}>{s}</div>)}</div>; }

export function MissionFilters({ filters, setFilters, domains }) { return <div className='filters'><input placeholder='Search missions' value={filters.search} onChange={(e) => setFilters((f) => ({ ...f, search: e.target.value }))} /><select value={filters.domain} onChange={(e) => setFilters((f) => ({ ...f, domain: e.target.value }))}><option value='all'>All domains</option>{domains.map((d) => <option key={d}>{d}</option>)}</select><select value={filters.risk} onChange={(e) => setFilters((f) => ({ ...f, risk: e.target.value }))}><option value='all'>All risk</option><option>High</option><option>Medium</option><option>Low</option></select><select value={filters.status} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value }))}><option value='all'>All status</option><option>New Mission</option><option>Evidence Requested</option><option>Client Responded</option><option>Follow-Up Submitted</option><option>Debrief Reviewed</option><option>Fundamentals Reviewed</option><option>Mission Complete</option><option>Escalated</option></select></div>; }

export function MissionQueuePanel({ missions, current, statuses, progressByMission, onOpenMission, filters, setFilters }) { const domains = [...new Set(missions.map((m) => m.domain))]; const filtered = missions.map((m, idx) => ({ m, idx })).filter(({ m, idx }) => (filters.domain === 'all' || m.domain === filters.domain) && (filters.risk === 'all' || m.riskLevel === filters.risk) && (filters.status === 'all' || statuses[idx] === filters.status) && (`${m.missionName} ${m.domain}`.toLowerCase().includes(filters.search.toLowerCase()))); return <aside className='panel queue-panel'><h3>Mission Queue</h3><MissionFilters filters={filters} setFilters={setFilters} domains={domains} /><div className='queue'>{filtered.map(({ m, idx }) => <button key={m.id} className={`mission-card ${current === idx ? 'active' : ''}`} onClick={() => onOpenMission(idx)}><header><h4>{m.domainIcon} {m.missionName}</h4><small>{m.domain}</small></header><div className='line'><RiskHeatBadge risk={m.riskLevel} /><span>{m.difficulty}</span><span>{m.estimatedTime}</span></div><div className='line'><span className='status-pill'>{statuses[idx]}</span></div><div className='line'>{m.frameworkTags.map((tag) => <FrameworkBadge key={tag} tag={tag} />)}</div><div className='progress'><div style={{ width: `${progressByMission[idx] || 0}%` }} /></div></button>)}</div></aside>; }
export const AuditCommandLayout = ({ header, left, center, right }) => <section className='command-layout'><header className='top-header'>{header}</header><div className='layout-grid'><div>{left}</div><main>{center}</main><div>{right}</div></div></section>;
export const EscalationMeter = ({ value }) => <section className='panel'><h3>Escalation Meter</h3><div className='progress danger'><div style={{ width: `${value}%` }} /></div></section>;
export function ScorePanel({ score, avgQuality, rank }) { return <section className='panel'><h3>Audit Score</h3><p className='score'>{score}</p><p>Avg Quality: {avgQuality}</p><p>Rank: {rank}</p></section>; }
export const MissionBrief = ({ mission, variant, modeCfg, onNext }) => <section className='panel mission-brief'><h2>{mission.missionName}</h2><div className='mode-badge'>{modeCfg.label}</div><p>{variant.clientScenario}</p><p><b>Objective:</b> {variant.auditObjective}</p><p><b>Mode:</b> {modeCfg.focus}</p><p><b>Hint:</b> {variant.hint}</p>{variant.discussionPrompt && <p><b>Discussion:</b> {variant.discussionPrompt}</p>}{variant.facilitatorNotes && <p><b>Facilitator notes:</b> {variant.facilitatorNotes}</p>}<button className='primary' onClick={onNext}>Open Evidence Request</button></section>;
export const EvidenceSelection = ({ evidenceOptions, selectedEvidence, setSelectedEvidence, onSubmit, minimumSelections }) => <section className='panel'><h3>Evidence Request</h3><p className='instruction'>Select evidence items that work together. A strong audit conclusion usually needs evidence for design, operation, timing, ownership, and exception handling.</p>{minimumSelections > 1 && selectedEvidence.length === 1 && <p className='warning'>A single evidence item is usually not enough to support an audit conclusion. Select additional evidence to validate design, operation, completeness, and exceptions.</p>}{evidenceOptions.map((x) => <label key={x.id} className='evidence-row'><input type='checkbox' checked={selectedEvidence.includes(x.id)} onChange={() => setSelectedEvidence((p) => p.includes(x.id) ? p.filter((id) => id !== x.id) : [...p, x.id])} /> {x.text}</label>)}<button className='primary' disabled={selectedEvidence.length < minimumSelections} onClick={onSubmit}>Submit Evidence</button></section>;
export const EvidenceEvaluation = ({ evaluated, pointsById }) => <section className='panel'><h3>Evidence Evaluation</h3>{evaluated.map((x) => <div key={x.id} className={`alert quality-${x.quality.toLowerCase()}`}><p><b>Quality:</b> <span className={`badge quality-badge quality-${x.quality.toLowerCase()}`}>{x.quality}</span></p><p>{x.text}</p><p><b>Points:</b> {pointsById[x.id]}</p><p><b>Why this matters:</b> {x.why}</p><p><b>What this evidence proves:</b> {x.proves}</p><p><b>What this evidence does not prove:</b> {x.limits}</p><p><b>Stronger evidence request:</b> {x.betterRequest}</p></div>)}</section>;
export const ClientResponseConsole = ({ evaluated }) => <section className='panel'><h3>Client Response</h3>{evaluated.map((x) => <div key={x.id} className='dialogue-card'><p><b>Client says:</b></p><blockquote>{x.clientResponse}</blockquote><p><b>Auditor note:</b> {x.auditorNote}</p></div>)}</section>;
export const FollowUpChallenge = ({ challenge, selectedOption, setSelectedOption, onSubmit }) => <section className='panel'><h3>Follow-up Challenge</h3><p>{challenge.followUpChallenge}</p><select value={selectedOption} onChange={(e) => setSelectedOption(e.target.value)}><option value=''>Select follow-up answer</option>{challenge.followUpOptions.map((o) => <option key={o} value={o}>{o}</option>)}</select><button className='primary' disabled={!selectedOption} onClick={onSubmit}>Submit Follow-up</button></section>;
export const FollowUpFeedbackPanel = ({ feedback, onContinue }) => <section className='panel'><h3>Follow-up Feedback</h3><p><b>Effective:</b> {feedback.correct ? 'Yes' : 'No'}</p><p><b>Why:</b> {feedback.message}</p><p><b>Stronger ask:</b> {feedback.strongerAsk}</p><p><b>Risk addressed:</b> {feedback.riskAddressed}</p><p><b>Request next:</b> {feedback.nextEvidence}</p><button className='primary' onClick={onContinue}>Continue to Debrief</button></section>;
const section = (label, value) => <div className='mini-section'><h5>{label}</h5><p>{Array.isArray(value) ? value.join(', ') : value}</p></div>;
export const ConsultantDebriefCard = ({ debrief }) => <section className='panel'><h3>Consultant Debrief</h3>{section('Risk Type', debrief.riskType)}{section('Assets Involved', debrief.assetsInvolved)}{section('Data Involved', debrief.dataInvolved)}{section('CIA Impact', debrief.ciaImpact)}{section('Audit Judgment', debrief.auditJudgment)}{section('Potential Finding', debrief.potentialFinding)}{section('Recommended Follow-Up', debrief.recommendedFollowUp)}{section('Consultant Lesson', debrief.consultantLesson)}{section('Common Mistake', debrief.commonMistake)}</section>;
export const FundamentalsCard = ({ lesson }) => <section className='panel'><h3>Fundamentals</h3>{section('What this means', lesson.whatItMeans)}{section('Why auditors care', lesson.whyAuditorsCare)}{section('Risk reduced', lesson.riskReduced)}{section('What good evidence looks like', lesson.goodEvidence)}{section('Common mistake', lesson.commonMistake)}{section('Simple analogy', lesson.analogy)}</section>;
export const FrameworkRelevanceCard = ({ mappings }) => <section className='panel'><h3>Framework Relevance</h3>{mappings.map((m) => <p key={m.controlId}><FrameworkBadge tag={m.framework} /> {m.controlId} — {m.controlName}: {m.relevance}</p>)}</section>;
