import React from 'react';

export const FrameworkBadge = ({ tag }) => <span className='badge framework'>{tag}</span>;
export const RiskHeatBadge = ({ risk }) => <span className={`badge risk ${risk.toLowerCase()}`}>{risk}</span>;
export const CIAImpactChips = ({ value }) => <div className='chips'>{String(value).split(',').map((v) => <span key={v} className='chip'>{v.trim()}</span>)}</div>;
const STEPS = ['Mission Brief', 'Evidence Request', 'Evidence Evaluation', 'Client Response', 'Follow-Up Challenge', 'Consultant Debrief', 'Fundamentals', 'Framework Relevance'];
export function ProgressStepper({ currentStep }) { return <div className='stepper'>{STEPS.map((s, i) => <div key={s} className={`step ${i === currentStep ? 'active' : i < currentStep ? 'done' : ''}`}>{s}</div>)}</div>; }

export function MissionFilters({ filters, setFilters, domains }) { return <div className='filters'><input placeholder='Search missions' value={filters.search} onChange={(e) => setFilters((f) => ({ ...f, search: e.target.value }))} /><select value={filters.scenarioType || 'all'} onChange={(e) => setFilters((f) => ({ ...f, scenarioType: e.target.value }))}><option value='all'>All categories</option><option value='Evidence Request'>Evidence Request</option><option value='CISO Review Challenge'>CISO Review Challenge</option></select><select value={filters.domain} onChange={(e) => setFilters((f) => ({ ...f, domain: e.target.value }))}><option value='all'>All domains</option>{domains.map((d) => <option key={d}>{d}</option>)}</select><select value={filters.risk} onChange={(e) => setFilters((f) => ({ ...f, risk: e.target.value }))}><option value='all'>All risk</option><option>High</option><option>Medium</option><option>Low</option></select><select value={filters.status} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value }))}><option value='all'>All status</option><option>New Mission</option><option>Evidence Requested</option><option>Client Responded</option><option>Follow-Up Submitted</option><option>Debrief Reviewed</option><option>Fundamentals Reviewed</option><option>Mission Complete</option><option>Escalated</option></select></div>; }

export function MissionQueuePanel({ missions, current, statuses, progressByMission, onOpenMission, filters, setFilters }) { const domains = [...new Set(missions.map((m) => m.domain))]; const filtered = missions.map((m, idx) => ({ m, idx })).filter(({ m, idx }) => (filters.scenarioType === 'all' || (filters.scenarioType === 'CISO Review Challenge' ? m.scenarioType === 'CISO Review Challenge' : !m.scenarioType)) && (filters.domain === 'all' || m.domain === filters.domain) && (filters.risk === 'all' || m.riskLevel === filters.risk) && (filters.status === 'all' || statuses[idx] === filters.status) && (`${m.missionName} ${m.domain}`.toLowerCase().includes(filters.search.toLowerCase()))); return <aside className='panel queue-panel'><h3>Mission Queue</h3><MissionFilters filters={filters} setFilters={setFilters} domains={domains} /><div className='queue'>{filtered.map(({ m, idx }) => <button key={m.id} className={`mission-card ${current === idx ? 'active' : ''}`} onClick={() => onOpenMission(idx)}><header><h4>{m.domainIcon} {m.missionName}</h4><small>{m.domain}</small></header><div className='line'><RiskHeatBadge risk={m.riskLevel} /><span>{m.difficulty}</span><span>{m.estimatedTime}</span></div><div className='line'><span className='status-pill'>{statuses[idx]}</span></div><div className='line'><span className='badge framework'>{m.scenarioType || 'Evidence Request'}</span>{m.frameworkTags.map((tag) => <FrameworkBadge key={tag} tag={tag} />)}</div><div className='progress'><div style={{ width: `${progressByMission[idx] || 0}%` }} /></div></button>)}</div></aside>; }
export const AuditCommandLayout = ({ header, left, center, right }) => <section className='command-layout'><header className='top-header'>{header}</header><div className='layout-grid'><div>{left}</div><main>{center}</main><div>{right}</div></div></section>;
export const EscalationMeter = ({ value }) => <section className='panel'><h3>Escalation Meter</h3><div className='progress danger'><div style={{ width: `${value}%` }} /></div></section>;
export function ScorePanel({ score, avgQuality, rank }) { return <section className='panel'><h3>Audit Score</h3><p className='score'>{score}</p><p>Avg Quality: {avgQuality}</p><p>Rank: {rank}</p></section>; }
export const MissionBrief = ({ mission, variant, modeCfg, onNext }) => <section className='panel mission-brief'><h2>{mission.missionName}</h2><div className='mode-badge'>{modeCfg.label}</div><p>{variant.clientScenario}</p><p><b>Objective:</b> {variant.auditObjective}</p><p><b>Mode:</b> {modeCfg.focus}</p><p><b>Hint:</b> {variant.hint}</p>{variant.discussionPrompt && <p><b>Discussion:</b> {variant.discussionPrompt}</p>}{variant.facilitatorNotes && <p><b>Facilitator notes:</b> {variant.facilitatorNotes}</p>}<button className='primary' onClick={onNext}>Open Evidence Request</button></section>;
export const EvidenceSelection = ({ evidenceOptions, selectedEvidence, setSelectedEvidence, onSubmit, minimumSelections }) => <section className='panel'><h3>Evidence Request</h3><p className='instruction'>Select evidence items that work together. A strong audit conclusion usually needs evidence for design, operation, timing, ownership, and exception handling.</p>{minimumSelections > 1 && selectedEvidence.length === 1 && <p className='warning'>A single evidence item is usually not enough to support an audit conclusion. Select additional evidence to validate design, operation, completeness, and exceptions.</p>}{evidenceOptions.map((x) => <label key={x.id} className='evidence-row'><input type='checkbox' checked={selectedEvidence.includes(x.id)} onChange={() => setSelectedEvidence((p) => p.includes(x.id) ? p.filter((id) => id !== x.id) : [...p, x.id])} /> {x.text}</label>)}<button className='primary' disabled={selectedEvidence.length < minimumSelections} onClick={onSubmit}>Submit Evidence</button></section>;
export const EvidenceEvaluation = ({ evaluated, pointsById }) => <section className='panel'><h3>Evidence Evaluation</h3>{evaluated.map((x) => <div key={x.id} className={`alert quality-${x.quality.toLowerCase()}`}><p><b>Quality:</b> <span className={`badge quality-badge quality-${x.quality.toLowerCase()}`}>{x.quality}</span></p><p>{x.text}</p><p><b>Points:</b> {pointsById[x.id]}</p><p><b>Why this matters:</b> {x.why}</p><p><b>What this evidence proves:</b> {x.proves}</p><p><b>What this evidence does not prove:</b> {x.limits}</p><p><b>Stronger evidence request:</b> {x.betterRequest}</p></div>)}</section>;
export const ClientResponseConsole = ({ evaluated }) => <section className='panel'><h3>Client Response</h3>{evaluated.map((x) => <div key={x.id} className='dialogue-card'><p><b>Client says:</b></p><blockquote>{x.clientResponse}</blockquote><p><b>Auditor note:</b> {x.auditorNote}</p></div>)}</section>;
export const FollowUpChallenge = ({ challenge, selectedOption, setSelectedOption, onSubmit }) => <section className='panel'><h3>Follow-up Challenge</h3><p>{challenge.followUpChallenge}</p><select value={selectedOption} onChange={(e) => setSelectedOption(e.target.value)}><option value=''>Select follow-up answer</option>{challenge.followUpOptions.map((o) => <option key={o} value={o}>{o}</option>)}</select><button className='primary' disabled={!selectedOption} onClick={onSubmit}>Submit Follow-up</button></section>;
export const FollowUpFeedbackPanel = ({ feedback, onContinue }) => <section className='panel'><h3>Follow-up Feedback</h3><p><b>Effective:</b> {feedback.correct ? 'Yes' : 'No'}</p><p><b>Why:</b> {feedback.message}</p><p><b>Stronger ask:</b> {feedback.strongerAsk}</p><p><b>Risk addressed:</b> {feedback.riskAddressed}</p><p><b>Request next:</b> {feedback.nextEvidence}</p><button className='primary' onClick={onContinue}>Continue to Debrief</button></section>;
const section = (label, value) => <div className='mini-section'><h5>{label}</h5><p>{Array.isArray(value) ? value.join(', ') : value}</p></div>;
export const ConsultantDebriefCard = ({ debrief }) => <section className='panel'><h3>Consultant Debrief</h3>{section('Risk Type', debrief.riskType)}{section('Assets Involved', debrief.assetsInvolved)}{section('Data Involved', debrief.dataInvolved)}{section('CIA Impact', debrief.ciaImpact)}{section('Audit Judgment', debrief.auditJudgment)}{section('Potential Finding', debrief.potentialFinding)}{section('Recommended Follow-Up', debrief.recommendedFollowUp)}{section('Consultant Lesson', debrief.consultantLesson)}{section('Common Mistake', debrief.commonMistake)}</section>;

const OSI_LAYERS = [
  { number: 7, name: 'Application', examples: 'APIs, DNS, SaaS, SIEM console, IAM portals' },
  { number: 6, name: 'Presentation', examples: 'TLS/SSL, encryption formats, certificates' },
  { number: 5, name: 'Session', examples: 'SSO sessions, VPN tunnels, session tokens' },
  { number: 4, name: 'Transport', examples: 'TCP, UDP, ports, load-balanced flows' },
  { number: 3, name: 'Network', examples: 'IP, routing, firewalls, segmentation, VPN' },
  { number: 2, name: 'Data Link', examples: 'Switches, VLANs, MAC addressing' },
  { number: 1, name: 'Physical', examples: 'Cabling, facilities, hardware, CCTV devices' },
];

const listText = (items) => Array.isArray(items) ? items.filter(Boolean).join(' ') : String(items || '');
const includesAny = (haystack, needles = []) => needles.some((needle) => haystack.includes(needle.toLowerCase()));
const sentence = (concept, scenario) => `${concept} appears in this scenario because the evidence question is testing ${scenario}. Use it to connect the technology to control design, operation, completeness, timing, ownership, and exception handling.`;

const conceptCatalog = [
  { id: 'iam', icon: '🔐', title: 'Identity and Access Management (IAM)', keywords: ['identity', 'access provisioning', 'jml', 'joiner', 'mover', 'leaver', 'entitlement', 'access request', 'deprovisioning', 'authentication', 'authorization'], domains: ['Identity & Access Management'], osi: [7,5], simple: 'IAM is the set of processes and systems that decide who a user is and what they are allowed to access.', analogy: 'Think of IAM as the front desk, badge office, and room-access list for a secure building.', consultant: 'IAM manages digital identities, approvals, entitlements, access changes, and removals so users receive only appropriate access for their role.', technical: 'IAM usually connects directories, HR feeds, workflow tools, applications, and access-control policies. Provisioning creates or changes accounts, authorization maps users to roles or groups, and deprovisioning removes access when employment or role need ends.', security: 'It reduces unauthorized access, orphan accounts, segregation-of-duty conflicts, and excessive privilege.', evidence: ['Access request tickets with requester, approver, timestamp, role, and system', 'Joiner-mover-leaver population from HR or identity source', 'Entitlement exports from in-scope applications', 'Deprovisioning timestamps and exception closure records', 'Access review sign-offs and remediation proof'], risks: ['Access granted before approval', 'Terminated users not removed promptly', 'Role changes not reflected in system access', 'No complete user population', 'Manual approvals with no audit trail'], questions: ['What is the authoritative identity source?', 'How are access approvals recorded?', 'How do you prove all leavers were removed?', 'Which privileged or sensitive roles require extra approval?', 'How are exceptions tracked and closed?'] },
  { id: 'pam', icon: '🗝️', title: 'Privileged Access Management (PAM)', keywords: ['privileged', 'admin', 'break-glass', 'emergency access', 'root', 'administrator', 'segregation-of-duty', 'sod'], domains: ['Identity & Access Management'], osi: [7,5], simple: 'PAM protects powerful accounts that can change systems, security settings, data, or other users access.', analogy: 'PAM is like keeping the master keys in a vault that records who checked them out and why.', consultant: 'PAM controls, approves, monitors, and records use of administrator access, especially high-risk or emergency access.', technical: 'PAM tools vault privileged credentials, rotate passwords or keys, broker sessions, enforce just-in-time access, record commands, and produce approval and session logs.', security: 'It limits the blast radius of compromised or misused administrator accounts.', evidence: ['Privileged account inventory', 'PAM policy and configuration screenshots', 'Session recordings or command logs', 'Break-glass approvals and retrospective reviews', 'Password or key rotation reports'], risks: ['Shared admin accounts', 'No session monitoring', 'Standing privilege instead of just-in-time access', 'Emergency access not reviewed', 'Privileged accounts missing from inventory'], questions: ['Which accounts are privileged?', 'Are admin credentials vaulted?', 'How often are privileged sessions reviewed?', 'How is emergency access approved and closed?', 'Can you show the complete privileged account population?'] },
  { id: 'mfa', icon: '📲', title: 'Multi-Factor Authentication (MFA)', keywords: ['mfa', 'multi-factor', '2fa', 'factor', 'authenticator', 'conditional access'], domains: ['Identity & Access Management', 'Cloud Security'], osi: [7,5], simple: 'MFA requires more than one proof of identity, such as a password plus an authenticator app or hardware token.', analogy: 'It is like needing both a bank card and a PIN before withdrawing cash.', consultant: 'MFA strengthens authentication by reducing reliance on passwords alone, especially for remote, privileged, cloud, and sensitive access.', technical: 'MFA combines factors: something you know, have, or are. Modern systems can enforce MFA through identity providers, conditional-access rules, risk scoring, device posture, and phishing-resistant methods.', security: 'It reduces account takeover risk from stolen, guessed, or reused passwords.', evidence: ['MFA policy settings', 'Conditional-access rules', 'User enrollment reports', 'Exception lists with approvals', 'Authentication logs showing MFA challenges'], risks: ['MFA not enabled for admins', 'Large exception groups', 'Legacy protocols bypass MFA', 'Weak SMS-only MFA for high-risk users', 'No periodic review of bypasses'], questions: ['Who is required to use MFA?', 'Which applications are covered?', 'What bypasses or exceptions exist?', 'Are privileged users protected by stronger methods?', 'How do logs prove MFA occurred?'] },
  { id: 'ad', icon: '🏢', title: 'Active Directory / Entra ID', keywords: ['active directory', 'azure ad', 'entra', 'directory', 'domain controller', 'group', 'tenant'], domains: ['Identity & Access Management', 'Cloud Security'], osi: [7,5,4], simple: 'Directory services store users, groups, devices, and policies used to sign in and authorize access.', analogy: 'It is the company phonebook and badge-permission database combined.', consultant: 'Active Directory and Entra ID are identity platforms that centralize authentication, group membership, policy enforcement, and application access.', technical: 'AD commonly uses Kerberos, LDAP, Group Policy, and domain controllers. Entra ID uses cloud identity, SSO, OAuth/OIDC/SAML integrations, conditional access, and tenant-wide policy controls.', security: 'A compromised directory can compromise many connected systems, so configuration, privilege, logging, and reviews matter heavily.', evidence: ['Group membership exports', 'Conditional-access settings', 'Directory role assignments', 'Authentication logs', 'User lifecycle workflow records'], risks: ['Excessive directory admin roles', 'Stale groups', 'Weak conditional-access coverage', 'Unmonitored directory changes', 'Orphaned guest accounts'], questions: ['Which directory is authoritative?', 'How are groups mapped to application roles?', 'Who can administer the tenant or domain?', 'How are guest users reviewed?', 'What logs alert on risky identity changes?'] },
  { id: 'siem', icon: '📊', title: 'Security Information and Event Management (SIEM)', keywords: ['siem', 'log monitoring', 'security monitoring', 'correlation', 'alert', 'detection', 'soc'], domains: ['Logging / Monitoring', 'Incident Response'], osi: [7], simple: 'A SIEM collects security logs from many systems and helps teams detect suspicious activity.', analogy: 'It is like a central security control room watching CCTV feeds, alarms, and door logs from every building.', consultant: 'A SIEM centralizes logs, correlates events, generates alerts, supports investigations, and provides evidence that monitoring controls operate.', technical: 'SIEM platforms ingest log sources, normalize events, apply correlation rules or analytics, enrich with threat context, create alerts, and retain searchable records for investigations and audit.', security: 'It helps detect attacks, policy violations, failed controls, and unusual activity before damage spreads.', evidence: ['Log source inventory', 'SIEM ingestion status', 'Correlation rule configuration', 'Alert triage tickets', 'Retention settings and sample searches'], risks: ['Critical logs not onboarded', 'Rules disabled or noisy', 'No alert ownership', 'Retention too short', 'No evidence alerts were investigated'], questions: ['Which systems send logs to the SIEM?', 'How is ingestion health monitored?', 'Who triages alerts?', 'What retention period applies?', 'Can you show alerts closed during the audit period?'] },
  { id: 'logging', icon: '🧾', title: 'Logs and Audit Trails', keywords: ['log', 'logging', 'audit trail', 'timestamp', 'monitoring', 'records', 'source population'], domains: ['Logging / Monitoring', 'Incident Response'], osi: [7,6,5,4,3,2,1], simple: 'Logs are timestamped records of what happened in a system.', analogy: 'Logs are like a building visitor book and CCTV timeline that help reconstruct events.', consultant: 'Logs provide objective evidence of activity, control operation, exceptions, and investigation steps.', technical: 'Systems generate authentication logs, application logs, admin logs, network logs, endpoint logs, database logs, and infrastructure logs. Quality depends on coverage, timestamps, integrity, retention, and correlation.', security: 'Without reliable logs, teams cannot prove what happened, detect abuse, or support audit conclusions.', evidence: ['Log samples for selected events', 'Retention configuration', 'Time synchronization settings', 'Log forwarding status', 'Admin activity reports'], risks: ['Logging disabled', 'Incomplete log sources', 'Clock drift', 'Logs overwritten too soon', 'No chain of custody for exported logs'], questions: ['Which events are logged?', 'Where are logs stored?', 'How long are they retained?', 'Are timestamps synchronized?', 'Who can alter or delete logs?'] },
  { id: 'edr', icon: '🛡️', title: 'Endpoint Detection and Response (EDR/XDR)', keywords: ['edr', 'xdr', 'endpoint', 'malware', 'agent', 'antivirus', 'device'], domains: ['Endpoint Security'], osi: [7,4,3,2], simple: 'EDR watches laptops, servers, and endpoints for suspicious behavior and helps respond quickly.', analogy: 'It is like a security guard and camera installed on every workstation.', consultant: 'EDR/XDR provides endpoint telemetry, detection alerts, response actions, and coverage reporting across protected devices.', technical: 'Agents collect process, file, registry, network, user, and command activity. XDR extends correlation across endpoint, identity, email, cloud, and network telemetry.', security: 'It reduces malware, ransomware, lateral movement, and uncontained compromise risk.', evidence: ['Agent coverage report', 'Policy configuration', 'Alert investigation records', 'Isolation or response action logs', 'Exclusion list approvals'], risks: ['Unmanaged endpoints', 'Disabled agents', 'Unapproved exclusions', 'Alerts not triaged', 'Servers outside coverage'], questions: ['What assets require EDR?', 'How do you track agent health?', 'Who investigates alerts?', 'What exclusions exist?', 'Can you show a recent detection workflow?'] },
  { id: 'firewall', icon: '🔥', title: 'Firewalls and Network Filtering', keywords: ['firewall', 'rule', 'network filtering', 'ports', 'allowlist', 'deny', 'internet ingress'], domains: ['Network Security'], osi: [3,4,7], simple: 'A firewall controls which network traffic is allowed or blocked.', analogy: 'It is like a security checkpoint that decides which vehicles may enter a restricted road.', consultant: 'Firewalls enforce network access rules between zones, users, systems, and the internet based on business need and risk.', technical: 'Traditional firewalls filter IPs, ports, and protocols. Next-generation firewalls may inspect applications, users, URLs, and threats. Cloud firewalls and security groups enforce similar rules in cloud networks.', security: 'They reduce unauthorized access, exposure of services, lateral movement, and internet attack paths.', evidence: ['Firewall rulebase export', 'Rule review sign-offs', 'Change tickets for rule changes', 'Network diagrams', 'Denied/allowed traffic logs'], risks: ['Overly broad any-any rules', 'Stale rules', 'No owner or business justification', 'Rules changed without approval', 'No periodic review'], questions: ['What does this rule allow?', 'Who owns the rule?', 'When was it last reviewed?', 'Does it expose sensitive systems?', 'Are denied traffic logs monitored?'] },
  { id: 'segmentation', icon: '🧱', title: 'Network Segmentation', keywords: ['segmentation', 'vlan', 'subnet', 'zone', 'dmz', 'lateral movement'], domains: ['Network Security', 'Cloud Security'], osi: [2,3,4], simple: 'Segmentation separates networks so one area cannot freely access every other area.', analogy: 'It is like dividing a building into locked rooms instead of giving everyone access to the whole building.', consultant: 'Segmentation limits communication between systems based on trust level, sensitivity, and business need.', technical: 'Segmentation can use VLANs, subnets, routes, ACLs, firewalls, microsegmentation, security groups, and zero-trust policies.', security: 'It limits attacker movement and protects sensitive zones such as production, payment, OT, and admin networks.', evidence: ['Network architecture diagrams', 'VLAN/subnet definitions', 'Firewall or ACL rules', 'Segmentation test results', 'Change approvals'], risks: ['Flat networks', 'Unclear zone ownership', 'Unvalidated rules', 'Shadow connections', 'No testing after changes'], questions: ['Which zones exist?', 'What traffic is allowed between zones?', 'How is segmentation tested?', 'Who approves new pathways?', 'What sensitive assets require isolation?'] },
  { id: 'vpn', icon: '🌐', title: 'Virtual Private Network (VPN)', keywords: ['vpn', 'remote access', 'tunnel', 'ipsec', 'ssl vpn'], domains: ['Network Security'], osi: [3,5,6,7], simple: 'A VPN creates an encrypted connection into a private network from another location.', analogy: 'It is like using a private protected tunnel into an office instead of walking through public streets.', consultant: 'VPN controls remote connectivity by authenticating users, encrypting traffic, and restricting what remote users can reach.', technical: 'VPNs use protocols such as IPsec or SSL/TLS, identity checks, device posture, split-tunnel rules, and network access policies.', security: 'It reduces exposure of internal systems while enabling remote work and support access.', evidence: ['VPN configuration', 'User access lists', 'MFA enforcement for VPN', 'Connection logs', 'Remote access policy'], risks: ['No MFA', 'Broad network access after connection', 'Stale VPN users', 'Split tunneling without risk acceptance', 'No monitoring of remote sessions'], questions: ['Who can use VPN?', 'Is MFA required?', 'What internal resources are reachable?', 'Are vendor accounts reviewed?', 'How are failed and successful logins monitored?'] },
  { id: 'encryption', icon: '🔒', title: 'Encryption and TLS/SSL', keywords: ['encryption', 'tls', 'ssl', 'certificate', 'encrypted', 'cryptographic'], domains: ['Cryptography / Data Protection', 'Cloud Security'], osi: [6,7], simple: 'Encryption scrambles data so only authorized parties with the right key can read it.', analogy: 'It is like locking a message in a box that only the intended recipient can open.', consultant: 'Encryption protects confidentiality and integrity for data in transit and at rest when implemented with approved algorithms, keys, and certificate management.', technical: 'TLS protects network sessions using certificates and key exchange. At-rest encryption protects disks, databases, backups, or objects. Effectiveness depends on algorithms, key length, certificate validity, rotation, and storage of keys.', security: 'It reduces data exposure if traffic is intercepted, storage is stolen, or backups are accessed improperly.', evidence: ['TLS configuration scan', 'Certificate inventory', 'Encryption policy', 'Database/storage encryption settings', 'Approved algorithm standards'], risks: ['Expired certificates', 'Weak protocols', 'Unencrypted sensitive data', 'Keys stored with encrypted data', 'No rotation or ownership'], questions: ['What data is encrypted?', 'Which protocols and algorithms are allowed?', 'Who manages certificates?', 'How are keys protected?', 'Are backups encrypted too?'] },
  { id: 'key-management', icon: '🧬', title: 'Key Management', keywords: ['key management', 'kms', 'key rotation', 'cryptographic key', 'hsm', 'certificate'], domains: ['Cryptography / Data Protection', 'Cloud Security'], osi: [6,7], simple: 'Key management controls the secret keys used to encrypt and decrypt data.', analogy: 'If encryption is a lock, key management is the secure key cabinet, checkout log, and replacement schedule.', consultant: 'Key management governs generation, storage, access, rotation, backup, revocation, and destruction of cryptographic keys.', technical: 'Organizations may use KMS, HSMs, certificate authorities, vaults, access policies, and rotation schedules to protect keys from misuse or loss.', security: 'Poor key control can make encryption meaningless or make data unrecoverable.', evidence: ['Key inventory', 'KMS/HSM access policies', 'Rotation records', 'Key custodian approvals', 'Revocation/destruction records'], risks: ['Keys shared broadly', 'No rotation', 'Keys hardcoded in code', 'Lost keys', 'No separation of duties'], questions: ['Where are keys stored?', 'Who can use or administer them?', 'How often are keys rotated?', 'How are emergency key events handled?', 'Are key changes logged?'] },
  { id: 'dlp', icon: '📤', title: 'Data Loss Prevention (DLP)', keywords: ['dlp', 'data loss', 'external sharing', 'sensitive data', 'classification'], domains: ['Data Protection / Privacy'], osi: [7,6], simple: 'DLP helps stop sensitive data from leaving approved channels.', analogy: 'It is like a mailroom scanner that checks whether confidential documents are being sent outside the company.', consultant: 'DLP detects, alerts, blocks, or monitors sensitive data movement across email, endpoints, SaaS, cloud storage, and networks.', technical: 'DLP uses content inspection, labels, regex, dictionaries, exact-data matching, user context, destinations, and policy actions such as block, warn, quarantine, or monitor.', security: 'It reduces accidental disclosure, insider leakage, and regulatory data exposure.', evidence: ['DLP policies', 'Alert and incident reports', 'Exception approvals', 'Data classification rules', 'Tuning and false-positive records'], risks: ['Monitor-only policies for critical data', 'No exception workflow', 'Poor classification coverage', 'Alerts not reviewed', 'Shadow channels not monitored'], questions: ['What data types are protected?', 'Which channels are covered?', 'What happens when a rule triggers?', 'Who approves exceptions?', 'How are false positives tuned?'] },
  { id: 'vuln', icon: '🩻', title: 'Vulnerability Management', keywords: ['vulnerability', 'scan', 'cve', 'cvss', 'remediation', 'security finding'], domains: ['Vulnerability Management'], osi: [7,6,5,4,3,2,1], simple: 'Vulnerability management finds and fixes weaknesses before attackers exploit them.', analogy: 'It is like regularly inspecting a building for broken locks, exposed wiring, and unsafe doors.', consultant: 'The process identifies vulnerabilities, prioritizes by risk, assigns owners, remediates or accepts exceptions, and verifies closure.', technical: 'Tools scan assets, detect software versions and misconfigurations, map CVEs, score severity, and track remediation against SLAs.', security: 'It reduces exploitability and supports patch, configuration, and risk treatment controls.', evidence: ['Scan reports', 'Asset coverage reports', 'Remediation tickets', 'SLA dashboards', 'Exception/risk acceptance approvals'], risks: ['Incomplete asset coverage', 'Critical findings past SLA', 'No owner assignment', 'False positives not validated', 'Exceptions not approved'], questions: ['What assets are scanned?', 'How often are scans run?', 'What SLAs apply?', 'Who owns remediation?', 'How is closure validated?'] },
  { id: 'patching', icon: '🧩', title: 'Patch Management', keywords: ['patch', 'patching', 'update', 'security update', 'hotfix'], domains: ['Vulnerability Management', 'Change Management'], osi: [7,6,5,4,3,2,1], simple: 'Patch management applies software updates that fix defects and security weaknesses.', analogy: 'It is like installing manufacturer safety repairs on a car before a known defect causes an accident.', consultant: 'Patch management plans, tests, approves, deploys, and verifies updates according to risk-based timelines.', technical: 'It relies on asset inventory, vulnerability intelligence, deployment tools, maintenance windows, rollback plans, exception approvals, and compliance reporting.', security: 'Unpatched systems are common entry points for ransomware, data theft, and service disruption.', evidence: ['Patch compliance reports', 'Change approvals', 'Deployment logs', 'Exception records', 'Post-patch validation results'], risks: ['Critical patches overdue', 'Unsupported systems', 'No testing or rollback', 'Servers excluded from tools', 'Manual patching with no proof'], questions: ['What patch SLAs apply?', 'How is criticality determined?', 'Which systems are excluded?', 'How do you verify successful installation?', 'How are exceptions approved?'] },
  { id: 'api', icon: '🔌', title: 'APIs', keywords: ['api', 'interface', 'integration', 'oauth', 'token', 'webhook'], domains: ['Application Security', 'Cloud Security'], osi: [7], simple: 'An API lets systems talk to each other using defined requests and responses.', analogy: 'It is like a restaurant menu: it tells you what you can order and how to ask for it.', consultant: 'APIs enable integrations but require authentication, authorization, input validation, logging, rate limits, and change control.', technical: 'APIs commonly use REST, GraphQL, SOAP, JSON, tokens, OAuth scopes, gateways, schemas, and versioning. Security depends on identity, validation, transport protection, and monitoring.', security: 'Poor API security can expose data, allow unauthorized actions, or create integration outages.', evidence: ['API inventory', 'Authentication and authorization configuration', 'Gateway policies', 'API logs', 'Change and testing records'], risks: ['Unauthenticated endpoints', 'Overbroad tokens', 'No rate limiting', 'Sensitive data in responses', 'Poor logging'], questions: ['Which APIs are exposed?', 'How are clients authenticated?', 'What scopes or roles are granted?', 'Are requests logged?', 'How are API changes tested?'] },
  { id: 'database', icon: '🗄️', title: 'Databases', keywords: ['database', 'sql', 'data store', 'payroll database', 'records', 'query'], domains: ['Database Security', 'BCP / DR / Backup'], osi: [7,6], simple: 'A database stores structured information that applications and users rely on.', analogy: 'It is like a highly organized filing cabinet with rules about who can open each drawer.', consultant: 'Database controls protect confidentiality, integrity, availability, access, logging, backup, and change to critical data stores.', technical: 'Databases use schemas, tables, queries, roles, transactions, indexes, replication, backups, encryption, and audit logging.', security: 'Weak database controls can cause data breaches, unauthorized changes, fraud, or unrecoverable data loss.', evidence: ['Database access exports', 'Privileged DBA review records', 'Audit log settings', 'Backup and restore records', 'Encryption configuration'], risks: ['Shared DBA accounts', 'Excessive direct access', 'No query/activity logging', 'Unencrypted sensitive data', 'Untested backups'], questions: ['Who has database access?', 'What privileged roles exist?', 'Are admin actions logged?', 'How is sensitive data encrypted?', 'How is restore capability tested?'] },
  { id: 'cloud', icon: '☁️', title: 'Cloud Services: SaaS, PaaS, and IaaS', keywords: ['cloud', 'saas', 'paas', 'iaas', 'tenant', 'security group', 'cloud service'], domains: ['Cloud Security'], osi: [7,6,5,4,3], simple: 'Cloud services provide applications, platforms, or infrastructure through a provider instead of only company-owned data centers.', analogy: 'SaaS is renting a finished office, PaaS is renting a workshop, and IaaS is renting building space and utilities.', consultant: 'Cloud governance defines shared responsibility, secure configuration, identity, logging, network controls, data protection, and vendor oversight.', technical: 'SaaS is managed applications, PaaS provides managed runtimes and databases, and IaaS provides compute, storage, and network primitives. Controls differ by responsibility split.', security: 'Misconfigured cloud services can expose data, bypass network controls, or weaken identity and logging.', evidence: ['Cloud architecture diagrams', 'Tenant configuration exports', 'Security posture reports', 'IAM role assignments', 'Logging and monitoring settings'], risks: ['Public storage', 'Overprivileged roles', 'Logs not enabled', 'No owner for cloud resources', 'Unclear shared responsibility'], questions: ['Which service model applies?', 'What does the provider manage?', 'What must the client configure?', 'How are cloud changes approved?', 'Which logs prove activity?'] },
  { id: 'backup', icon: '🛟', title: 'Backups and Restore Testing', keywords: ['backup', 'restore', 'rto', 'rpo', 'dr', 'disaster recovery', 'recovery'], domains: ['BCP / DR / Backup'], osi: [7,6,3,1], simple: 'Backups are copies of data, and restore testing proves those copies can actually be used after a failure.', analogy: 'It is like packing a spare parachute and periodically proving it opens before an emergency.', consultant: 'Backup controls protect availability and recoverability, but audit evidence must prove successful restoration against RTO and RPO expectations.', technical: 'Backup programs define scope, schedules, retention, encryption, immutability, offsite storage, restore procedures, dependency mapping, and recovery validation.', security: 'They reduce outage, ransomware, accidental deletion, and data-loss impact.', evidence: ['Backup job reports', 'Restore test results', 'RTO/RPO measurements', 'Failed-test remediation tickets', 'Business owner acceptance'], risks: ['Green backup jobs but no restore proof', 'Critical systems omitted', 'Backups not encrypted', 'RTO/RPO not measured', 'Failed tests not remediated'], questions: ['What systems are backed up?', 'When was the last restore test?', 'Were RTO and RPO met?', 'Who validated the restored service?', 'What failures remain open?'] },
  { id: 'incident', icon: '🚨', title: 'Incident Response', keywords: ['incident', 'response', 'ir', 'dfir', 'forensic', 'lessons learned', 'p1', 'root cause'], domains: ['Incident Response'], osi: [7,6,5,4,3,2,1], simple: 'Incident response is the organized process for handling security events that may harm the business.', analogy: 'It is like a fire drill and emergency response plan for cyber events.', consultant: 'IR defines preparation, triage, containment, eradication, recovery, communication, evidence handling, and lessons learned.', technical: 'IR uses playbooks, severity criteria, escalation paths, forensic collection, ticketing, communication plans, root-cause analysis, and corrective actions.', security: 'It reduces dwell time, damage, regulatory exposure, and repeat incidents.', evidence: ['Incident response plan', 'Incident tickets', 'Timeline and containment records', 'Lessons-learned reports', 'Corrective-action closure'], risks: ['No tested playbooks', 'Unclear severity criteria', 'Late escalation', 'No chain of custody', 'Lessons learned not tracked'], questions: ['How are incidents classified?', 'Who approves escalation?', 'How is evidence preserved?', 'What playbooks are tested?', 'How are corrective actions closed?'] },
  { id: 'access-reviews', icon: '✅', title: 'Access Reviews / Recertification', keywords: ['access review', 'recertification', 'review', 'attestation', 'sign-off', 'entitlement review'], domains: ['Identity & Access Management'], osi: [7], simple: 'Access reviews ask owners to confirm users still need the access they have.', analogy: 'It is like periodically checking who still needs keys to each room.', consultant: 'Access reviews validate appropriateness of entitlements and require timely remediation of inappropriate access.', technical: 'Reviews use user and role populations, owner attestations, exception workflows, reminders, escalations, and remediation tracking.', security: 'They reduce stale access, excessive permissions, and segregation-of-duty violations.', evidence: ['Review campaign scope', 'Reviewer sign-offs', 'User entitlement lists', 'Revocation tickets', 'Late or exception reports'], risks: ['Incomplete application scope', 'Rubber-stamp approvals', 'No revocation proof', 'Late reviews', 'No privileged access focus'], questions: ['What systems are reviewed?', 'Who reviews access?', 'How is the population generated?', 'What happens to rejected access?', 'Are privileged roles reviewed separately?'] },
  { id: 'data-classification', icon: '🏷️', title: 'Data Classification', keywords: ['classification', 'confidential', 'restricted', 'privacy', 'data governance'], domains: ['Data Protection / Privacy'], osi: [7], simple: 'Data classification labels information by sensitivity so the right protections can be applied.', analogy: 'It is like marking documents public, internal, confidential, or top secret before deciding where they can go.', consultant: 'Classification drives security requirements for access, encryption, retention, DLP, sharing, and incident handling.', technical: 'Programs define labels, owners, handling rules, automated/manual tagging, discovery, exception handling, and enforcement integrations.', security: 'Without classification, teams may under-protect sensitive data or overburden low-risk data.', evidence: ['Classification policy', 'Data inventory', 'Labeling rules', 'DLP mappings', 'Exception approvals'], risks: ['Unlabeled sensitive data', 'Inconsistent labels', 'No owner accountability', 'Controls not mapped to labels', 'No periodic review'], questions: ['What classification levels exist?', 'How is data labeled?', 'Who owns data sets?', 'Which controls map to each label?', 'How are exceptions approved?'] },
  { id: 'change', icon: '🔁', title: 'Change Management', keywords: ['change', 'change management', 'approval', 'release', 'deployment', 'emergency change'], domains: ['Change Management'], osi: [7,6,5,4,3,2,1], simple: 'Change management controls how systems are modified so changes are approved, tested, and traceable.', analogy: 'It is like requiring a work order before changing electrical wiring in a building.', consultant: 'Change control ensures modifications are authorized, tested, implemented, reviewed, and documented with emergency exceptions controlled.', technical: 'A change process uses requests, risk ratings, approvals, test evidence, implementation logs, backout plans, CAB review, and post-implementation validation.', security: 'It reduces outages, unauthorized changes, insecure configuration, and untracked production modifications.', evidence: ['Change tickets', 'Approval records', 'Test results', 'Implementation logs', 'Emergency change reviews'], risks: ['Changes before approval', 'No testing evidence', 'Emergency changes not reviewed', 'Backout plans missing', 'Production access bypasses workflow'], questions: ['What changes require approval?', 'How are emergency changes handled?', 'Where is testing recorded?', 'Who can deploy to production?', 'How are failed changes tracked?'] },
  { id: 'vendor', icon: '🤝', title: 'Third-Party / Supplier Risk Management', keywords: ['vendor', 'supplier', 'third-party', 'contract', 'soc report', 'attestation', 'supplier'], domains: ['Third-Party Risk'], osi: [7,6,5,4,3,2,1], simple: 'Third-party risk management checks whether suppliers that support the business are secure and reliable.', analogy: 'It is like verifying a delivery company is licensed, insured, and still meeting safety rules after hiring them.', consultant: 'Supplier controls manage onboarding, due diligence, contractual security clauses, access, monitoring, reassessment, and offboarding.', technical: 'Programs use risk tiers, questionnaires, attestations, SOC/ISO reports, vulnerability notices, contract terms, SLA monitoring, and periodic reassessments.', security: 'Suppliers can create data, access, availability, and compliance risk even when systems are outside direct control.', evidence: ['Vendor risk assessment', 'SOC/ISO reports', 'Contract security clauses', 'Reassessment records', 'Supplier access reviews'], risks: ['Expired attestations', 'No periodic reassessment', 'Supplier access not reviewed', 'Missing security clauses', 'No exit plan'], questions: ['What risk tier is the supplier?', 'What data or access do they have?', 'When was reassessment completed?', 'What contractual controls apply?', 'How are supplier issues tracked?'] },
  { id: 'cctv', icon: '🎥', title: 'Physical Security and CCTV', keywords: ['cctv', 'physical', 'facility', 'badge', 'camera', 'time synchronized'], domains: ['Physical Security'], osi: [1,7], simple: 'Physical security protects buildings, rooms, hardware, and people from unauthorized physical access.', analogy: 'It is the locks, guards, cameras, and visitor logs for technology spaces.', consultant: 'Physical controls use badges, visitor management, CCTV, environmental controls, and monitoring to protect systems and evidence integrity.', technical: 'Controls include access readers, camera coverage, retention settings, NTP/time synchronization, alarm monitoring, visitor workflows, and periodic reviews.', security: 'Physical compromise can bypass logical controls, tamper with systems, or invalidate investigation evidence.', evidence: ['Badge access logs', 'CCTV retention settings', 'Camera coverage map', 'Visitor logs', 'Time synchronization settings'], risks: ['Camera blind spots', 'CCTV time not synchronized', 'No visitor escort proof', 'Logs retained too briefly', 'Badge access not reviewed'], questions: ['What areas are restricted?', 'Who can enter?', 'How long is footage retained?', 'Are camera timestamps accurate?', 'How are physical access exceptions reviewed?'] },
  { id: 'governance', icon: '🧭', title: 'Governance, Risk, Compliance, and Audit Evidence', keywords: ['governance', 'risk', 'compliance', 'audit', 'evidence', 'policy', 'control', 'procedure', 'isms', 'clause', 'management review', 'corrective action'], domains: ['CISO Review Challenge'], osi: [7], simple: 'Governance defines who is accountable, what rules apply, how risk decisions are made, and what proof shows controls work.', analogy: 'It is like the rulebook, scorecard, meeting minutes, and signed decisions for running a secure organization.', consultant: 'GRC connects policies, controls, risks, evidence, owners, reviews, and findings into defensible assurance conclusions.', technical: 'GRC programs maintain control libraries, risk registers, policies, workflows, approvals, evidence repositories, metrics, management reviews, corrective actions, and audit trails.', security: 'It prevents vague ownership, unsupported conclusions, missed requirements, and unresolved risk treatment.', evidence: ['Policies and procedures', 'Risk register updates', 'Management review minutes', 'Control test evidence', 'Corrective-action trackers'], risks: ['Policy exists but no operating proof', 'No owner or review cadence', 'Stale risk register', 'Actions not closed', 'Generic assessment wording'], questions: ['What requirement is being tested?', 'Who owns the control?', 'What objective evidence exists?', 'How often is it reviewed?', 'What decision or corrective action resulted?'] },
];

const domainFallbackConcepts = {
  'Identity & Access Management': ['iam', 'mfa', 'pam', 'ad', 'access-reviews'],
  'Network Security': ['firewall', 'segmentation', 'vpn', 'logging'],
  'Logging / Monitoring': ['siem', 'logging', 'incident'],
  'Endpoint Security': ['edr', 'logging', 'incident'],
  'Cryptography / Data Protection': ['encryption', 'key-management', 'data-classification'],
  'Data Protection / Privacy': ['data-classification', 'dlp', 'encryption'],
  'Vulnerability Management': ['vuln', 'patching', 'change'],
  'Application Security': ['api', 'database', 'logging', 'change'],
  'Cloud Security': ['cloud', 'iam', 'mfa', 'logging', 'segmentation'],
  'Database Security': ['database', 'encryption', 'backup', 'iam'],
  'Change Management': ['change', 'logging', 'iam'],
  'Third-Party Risk': ['vendor', 'iam', 'vpn', 'cloud'],
  'BCP / DR / Backup': ['backup', 'database', 'incident', 'logging'],
  'Incident Response': ['incident', 'siem', 'logging', 'edr'],
  'Physical Security': ['cctv', 'logging'],
  'CISO Review Challenge': ['governance', 'logging', 'vendor', 'cloud'],
};

const getScenarioText = (mission, variant) => [
  mission?.domain,
  mission?.missionName,
  variant?.clientScenario,
  variant?.auditObjective,
  variant?.hint,
  mission?.consultantDebrief?.assetsInvolved,
  mission?.consultantDebrief?.dataInvolved,
  mission?.consultantDebrief?.riskType,
  mission?.consultantDebrief?.recommendedFollowUp,
  mission?.reviewerChallenge?.fictionalScenario,
  mission?.reviewerChallenge?.weakObservation,
  mission?.reviewerChallenge?.evidenceToRequest,
  ...(variant?.evidenceOptions || []).flatMap((ev) => [ev.text, ev.clientResponse, ev.followUpChallenge, ev.bestFollowUpAnswer, ev.riskAddressed, ev.nextEvidence]),
].map(listText).join(' ').toLowerCase();

const selectFundamentalConcepts = (mission, variant) => {
  const text = getScenarioText(mission, variant);
  const matched = conceptCatalog.filter((concept) => includesAny(text, concept.keywords) || concept.domains?.includes(mission?.domain));
  const fallbackIds = domainFallbackConcepts[mission?.domain] || ['governance', 'logging'];
  const fallback = fallbackIds.map((id) => conceptCatalog.find((concept) => concept.id === id)).filter(Boolean);
  return [...new Map([...matched, ...fallback].map((concept) => [concept.id, concept])).values()].slice(0, 8);
};

const OSIModel = ({ activeLayers }) => <div className='osi-model' aria-label='OSI model placement'>{OSI_LAYERS.map((layer) => {
  const active = activeLayers.includes(layer.number);
  return <div key={layer.number} className={`osi-layer ${active ? 'active' : ''}`}><span className='osi-number'>L{layer.number}</span><span><b>{layer.name}</b><small>{layer.examples}</small></span>{active && <span className='osi-hit'>Primary fit</span>}</div>;
})}</div>;

const BulletList = ({ items }) => <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>;
const ConceptBlock = ({ concept, lesson, scenarioFocus }) => <details className='fundamental-card' open={concept.id === 'governance' || concept.id === 'iam'}><summary><span className='fundamental-icon'>{concept.icon}</span><span><b>{concept.title}</b><small>Layers {concept.osi.join(', ')} · evidence-ready explanation</small></span></summary><div className='fundamental-content'><div className='learning-grid'><div className='learning-note beginner'><h5>Beginner explanation</h5><p>{concept.simple}</p></div><div className='learning-note analogy'><h5>Real-world analogy</h5><p>{concept.analogy}</p></div><div className='learning-note consultant'><h5>Consultant explanation</h5><p>{concept.consultant}</p><p className='say-this'><b>If a client asks “Can you explain this?” say:</b> “{concept.consultant} For this evidence request, I am looking for objective proof that the control operated during the audit period, covered the right population, had accountable ownership, and resolved exceptions.”</p></div><div className='learning-note technical'><h5>Technical deep dive</h5><p>{concept.technical}</p></div></div><h5>OSI model placement</h5><OSIModel activeLayers={concept.osi} /><div className='audit-angle-grid'><div className='evidence-box'><h5>Evidence usually requested</h5><BulletList items={concept.evidence} /></div><div className='risk-box'><h5>Common risks / gaps</h5><BulletList items={concept.risks} /></div></div><div className='learning-grid compact'><div className='learning-note security'><h5>Why it matters in security</h5><p>{concept.security}</p></div><div className='learning-note audit'><h5>Evidence / audit angle</h5><p>{lesson?.goodEvidence}</p></div><div className='learning-note questions'><h5>Client questions to ask</h5><BulletList items={concept.questions} /></div><div className='learning-note scenario'><h5>How it connects to this scenario</h5><p>{sentence(concept.title, scenarioFocus)}</p></div></div></div></details>;

export const FundamentalsCard = ({ lesson, mission, variant }) => {
  const concepts = selectFundamentalConcepts(mission, variant);
  const scenarioFocus = mission?.consultantDebrief?.riskType || variant?.auditObjective || mission?.missionName || 'the stated audit objective';
  return <section className='panel fundamentals-panel'><div className='fundamentals-hero'><p className='eyebrow'>Cybersecurity study guide + client-readiness coach</p><h3>Fundamentals</h3><p>This tab explains the technologies, terms, controls, and audit concepts behind the current scenario so you can answer basic client questions without freezing.</p><div className='takeaway-row'><span>🎯 Scenario focus: {scenarioFocus}</span><span>🧪 Evidence focus: design, operation, completeness, timing, ownership, exceptions</span></div></div><div className='fundamentals-baseline'><h4>Control lesson for this mission</h4>{section('What this means', lesson.whatItMeans)}{section('Why auditors care', lesson.whyAuditorsCare)}{section('Risk reduced', lesson.riskReduced)}{section('Common mistake', lesson.commonMistake)}</div><div className='concept-count'>{concepts.length} scenario-relevant concepts detected</div>{concepts.map((concept) => <ConceptBlock key={concept.id} concept={concept} lesson={lesson} scenarioFocus={scenarioFocus} />)}</section>;
};
export const FrameworkRelevanceCard = ({ mappings }) => <section className='panel'><h3>Framework Relevance</h3>{mappings.map((m) => <p key={m.controlId}><FrameworkBadge tag={m.framework} /> {m.controlId} — {m.controlName}: {m.relevance}</p>)}</section>;
export const ReviewerChallengePanel = ({ challenge, selectedOption, setSelectedOption, onSubmit }) => <section className='panel'><h3>CISO Review Challenge</h3><p><b>Scenario:</b> {challenge.fictionalScenario}</p><p><b>Weak observation:</b> {challenge.weakObservation}</p><p><b>{challenge.reviewerQuestion}</b></p><select value={selectedOption} onChange={(e) => setSelectedOption(e.target.value)}><option value=''>Select your reviewer decision</option>{challenge.answerOptions.map((o) => <option key={o} value={o}>{o}</option>)}</select><button className='primary' disabled={!selectedOption} onClick={onSubmit}>Submit Review</button></section>;
export const ReviewerFeedbackPanel = ({ challenge, selectedOption, onContinue }) => <section className='panel'><h3>Reviewer Feedback</h3><p><b>Detailed feedback:</b> {challenge.feedbackForEachOption[selectedOption]}</p>{section('Missed gaps', challenge.missedGaps)}{section('Stronger observation', challenge.strongerObservation)}{section('Stronger gap statement', challenge.strongerGapStatement)}{section('Evidence to request', challenge.evidenceToRequest)}{section('Maturity rating challenge', challenge.maturityRatingChallenge)}{section('Consultant lesson', challenge.consultantLesson)}<button className='primary' onClick={onContinue}>Continue</button></section>;
